name: Move JARS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move jars
      run: mv out/*/*/*.jar .
    - name: git Actions
      # You may pin to the exact commit or the version.
      # uses: srt32/git-actions@e958482c32696439aff04bc931155b00e2551474
      uses: srt32/git-actions@v0.0.3
    - run: git commit -m 'Moved jar'
    - run: git push -U origin master
