name: Move JARS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: git pull
    - name: Make shit commit
      run: echo "\nThis was created AUTOMATICALLY." >> README.md
    - name: Move jars
      run: cp out/*/*/*.jar .
    - run: git config --global user.email "k.chulakov97@gmail.com"
    - run: git config --global user.name "ulyanovskk"
    - run: git add README.md
    - run: git add server.jar
    - run: git add client.jar
    - run: git commit -m 'Moved jars'
    - run: git push -u origin master
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf lab6
          rm -rf script
          echo "#!/bin/sh" >> script
          echo "git clone https://github.com/ulyanovskk/lab6.git" >> script
          chmod 700 script
          ./script
          
