name: Move JARS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: git config --global user.email ${{ secrets.EMAIL }}
    - run: git config --global user.name ${{ secrets.NAME }}
    - run: git pull origin master
    - name: Make shit commit
      run: echo "This was created AUTOMATICALLY." >> README.md
    - name: Move jars
      run: cp out/*/*/*.jar .
    - run: git add README.md
    - run: git add server.jar
    - run: git add client.jar
    - run: git commit -m 'Moved jars'
    - run: git push -u origin master
